# import relevant libraries

In [13]:
import numpy as np

# scalar


In [14]:
s = 5 #int or float will do job to declare scalar 

In [15]:
s

5

# vector

In [16]:
v = np.array([-5,-2,4])

In [5]:
v #by default , v is a row vector 

array([-5, -2,  4])

# matrices

In [7]:
m = np.array([[5,12,6],[-3,0,14]])

In [8]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [9]:
type(s)

int

In [10]:
type(v) # one dimensional array 

numpy.ndarray

In [11]:
type(m) #two dimensional array 

numpy.ndarray

In [12]:
s_array = np.array(5) #if want s to be consistent with others 

In [17]:
type(s_array) 

numpy.ndarray

# Data shapes

In [18]:
m.shape

(2, 3)

In [19]:
v.shape #in memory of computer this object has 3 elements 

(3,)

In [20]:
v.reshape(1,3) #reshape gives an array a new shape without changing its data row vector

array([[-5, -2,  4]])

In [21]:
v.reshape(3,1) #column vector 

array([[-5],
       [-2],
       [ 4]])