In [1]:
import tensorflow as tf
import pandas as pd

# initialization of tensors

In [2]:
x = tf.constant(4, shape = (1,1)) #can also specify the dtype 'e.g change to float32'
print(x)

tf.Tensor([[4]], shape=(1, 1), dtype=int32)


In [3]:
x = tf.constant([[1,2,3],[4,5,6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [4]:
x = tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [5]:
x = tf.eye(3) #eye for identity matrix 
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [6]:
#from a normal distribution 
x = tf.random.normal((3,3), mean = 0, stddev = 1) 
print(x) #gets values between -1 and 1 

tf.Tensor(
[[ 1.3143544  -1.5949203  -0.6956662 ]
 [-1.2280632  -1.0934286  -0.13861321]
 [-0.9716111  -0.37328425  0.9622611 ]], shape=(3, 3), dtype=float32)


In [7]:
#uniform distribution
x = tf.random.uniform((1,3), minval = 0, maxval = 1)
print(x)

tf.Tensor([[0.82984376 0.8657161  0.27963138]], shape=(1, 3), dtype=float32)


# mathematical operations 

In [19]:
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])

In [20]:
z = tf.add(x,y) #adds each element wise 
z = x + y  #both equations are equivelent 
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [21]:
z = tf.subtract(x,y)
z = x - y 
print(z)

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [22]:
z = tf.divide(x,y)
z = x / y
print(z)

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [23]:
z = tf.multiply(x,y)
z = x * y
print(z)

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [13]:
z = x ** 5 #element wise expontentiation 
print(z)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [25]:
z = tf.tensordot(x, y, axes = 1)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [27]:
x= tf.random.normal((2,3))
y= tf.random.normal((3,4))

In [28]:
z = tf.matmul(x,y)
print(z)

tf.Tensor(
[[-0.10756827 -0.12699196  0.08879364  0.17527226]
 [-0.52414185  0.26615083  0.98801553  1.2508112 ]], shape=(2, 4), dtype=float32)


# Indexing of a Tensor

In [34]:
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])

In [36]:
print(x[1:]) #prints everything except index position 0 

tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)


In [37]:
print(x[::2]) #skips every other element 

tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)


In [38]:
print(x[::-1]) #reverse order

tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [43]:
indices = tf.constant([0,3])
x_ind = tf.gather(x, indices)
print(x_ind)

tf.Tensor([0 2], shape=(2,), dtype=int32)


In [46]:
x = tf.constant([[1,2],[3,4],[5,6]])
#if want to get first row of all elements 
x[0] #or #(x[0,:])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

In [47]:
#if want to get first two rows
x[0:2] #non inclusive 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>